image: php:7.3.3
pipelines:
  default:
    - step:
        script:
          # Register Debian package repository archive, for forward compatibility
          - echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
          - sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list
          - apt-get -o Acquire::Check-Valid-Until=false update
          # Install git, zip
          - apt-get install -y zip git
          # Install composer and project module dependencies
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          # Copy project folder to be zipped: build -> plugin name
          - cd $BITBUCKET_CLONE_DIR && cd ..
          - cp -r build $BITBUCKET_REPO_SLUG
          # Create zip package
          - export ZIP_NAME=$BITBUCKET_REPO_SLUG-latest.zip
          - zip -r $ZIP_NAME $BITBUCKET_REPO_SLUG -x "**/*node_modules*" "**/*.git*" "**/_*" "**/.hardlinks" "*pipelines.yml" "**/.gitignore" "**/composer.json" "**/composer.lock" "**/*sources*" "**/*.sass-cache*" "**/.babelrc" "**/package.json" "**/package-lock.json" "**/README.md"
          - echo "Created $ZIP_NAME"
          - ls -la
          # Deploy to Downloads
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"$ZIP_NAME"
  tags:
    '*':
      - step:
          script:
            #
            # Same as above, but with BITBUCKET_TAG instead of BITBUCKET_COMMIT
            #
            # Register Debian package repository archive, for forward compatibility
            - echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
            - sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list
            - apt-get -o Acquire::Check-Valid-Until=false update
            # Install git, zip
            - apt-get install -y zip git
            # Install composer and project module dependencies
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install
            # Copy project folder to be zipped: build -> plugin name
            - cd $BITBUCKET_CLONE_DIR && cd ..
            - cp -r build $BITBUCKET_REPO_SLUG
            # Create zip package
            - export ZIP_NAME=$BITBUCKET_REPO_SLUG-$BITBUCKET_TAG.zip
            - zip -r $ZIP_NAME $BITBUCKET_REPO_SLUG -x "**/*node_modules*" "**/*.git*" "**/_*" "**/.hardlinks" "*pipelines.yml" "**/.gitignore" "**/composer.json" "**/composer.lock" "**/*sources*" "**/*.sass-cache*" "**/.babelrc" "**/package.json" "**/package-lock.json" "**/README.md"
            - echo "Created $ZIP_NAME"
            - ls -la
            # Deploy to Downloads
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"$ZIP_NAME"
